Clean up Program.cs & DI
HomeDeploys/Issueneter pull request #27
Opened 2023-04-08 23:40 UTC by hrrrrustic

2023-04-08 23:41 UTC, hrrrrustic commented on Issueneter.Host/Composition/IModule.cs
> +}
Чет пришло в голову такое +-, но как-то хз, снес имплементацию с модулей пока, чекни как тебе

2023-04-09 08:34 UTC, Bibletoon requested changes
Основная претензия это применение Minimal Api и обилие логики в контроллере, остальное более косметическое

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Host/Composition/IModule.cs
> +}
Ну основная проблема с таким интерфейсом что он не даёт какого-то ощутимого профита, но при этом заставляет реализовывать оба метода даже если тебе WebApplication не нужен. Так что либо засплитить на два интерфейса - что тоже звучит плохо, либо просто по старинке писать экстеншены придерживаясь одного формата без интерфейса

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Host/Modules/SwaggerModule.cs
> +        IConfigurationRoot configuration)
Мне как-то не очень нравится когда на новую строчку переносится один параметр, как-то не консистентно. Кажется что приятнее выглядит каждый параметр на своей строке

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Host/Program.cs
>  builder.Configuration.AddJsonFile("appsettings.Local.json");
Может добавить if на дебаг мод, чтобы при релизе не пытаться добавлять несуществующий файл

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Host/Program.cs
>      .AddSingleton<IMessageFormatter<PullRequest>, PullRequestMessageFormatter>();
Это же вроде не нужно 🤔

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Host/Program.cs
> +    .AddTelegramModule(env, config);
Кажется можно объединить в одну цепочку, чтобы потом не потерять случайно регистрацию ScanRunner'а

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Host/Routes/ScanRoutes.cs
> +    private static async Task<IResult> GetScan(ScanStorage storage, long scanId)
В одном месте store а в другом storage

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Host/Routes/ScanRoutes.cs
> +        app.MapPost("/{source}/scan", async (string source, ScanStorage store, [FromBody] AddNewRepoScanRequest request)
А тут вообще везде store, хотя класс Storage

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Host/Routes/ScanRoutes.cs
> +    }
Кажется что идея MinimalApi в том, чтобы просто вызывать условно методы сервисов с небольшой доп. логикой, а тут получается почти 0 отличий от контроллеров (просто размечаем не атрибутами, а лямбдами). 

Ну и кажется что как-то слишком много логики для контроллера

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Persistence/IDbConnectionFactory.cs
> +    public IDbConnection GetConnection() => new NpgsqlConnection(_connectionString);
Удачи потом без IDE найти этот класс

2023-04-09 08:34 UTC, Bibletoon commented on Issueneter.Runner/ScanRunner.cs
> +            return;
Надо будет логи прикрутить...

2023-04-09 09:56 UTC, hrrrrustic commented on Issueneter.Runner/ScanRunner.cs
> +            return;
Надо будет

2023-04-09 09:56 UTC, hrrrrustic commented on Issueneter.Persistence/IDbConnectionFactory.cs
> +    public IDbConnection GetConnection() => new NpgsqlConnection(_connectionString);
Да вроде через CTRL+T нашлось спокойно, потом подвину отдельно куда-нибдудь

2023-04-09 10:01 UTC, hrrrrustic commented on Issueneter.Host/Composition/IModule.cs
> +}
Ну хз, засплитить вроде ок
Но из профита как бы да, только немного едиообразности и подсветочки красивой

2023-04-09 10:03 UTC, hrrrrustic commented on Issueneter.Host/Routes/ScanRoutes.cs
> +    }
Ну это понятно, пока просто из Program.cs унес, чтобы не мешалось, потом как-нибудь по пути разнесем нормально

2023-04-09 10:22 UTC, Bibletoon approved these changes

2023-04-09 10:34 UTC, merged